export function HeroShape() {
  return (
    <div
      className="
        pointer-events-none
        absolute
        inset-0
        z-0
        hidden
        overflow-hidden
        lg:block
      "
      aria-hidden="true"
    >
      <img
        src="/landing/hero-wave-bg1.svg"
        alt=""
        draggable={false}
        className="
          h-full
          w-full
          select-none
          object-cover
          object-center
        "
      />
    </div>
  );
}
